### ISSUE TITLE
Cannot install theme

### ISSUE THREAD

**Issue by ghost** [catppuccin/infinity#1]
I was trying to install this theme but when I click in `Import Theme` it says `Cannot find data in clipboard`, and I have copied all the file.

**Comment by nekoxuee** [comment]
Seems to be a bug from Infinity itself. Docile-Alligator/Infinity-For-Reddit#1030
Try to paste the contents in your phone notes app or similar (I used Google keep) and then copy it from there.

**Comment by ghost** [comment]
Okay, now it works, thanks!
