### ISSUE TITLE
OLED version

### ISSUE THREAD

**Issue by ttmx** [catppuccin/infinity#3]
Hey! I'd like to request an OLED version of this theme, for battery saving on mobile.

I made my own but am not sure it's up to standards, I just changed some backgrounds to black from Mocha. Here is what I got.

`{"archivedTint":"#FFCBA6F7","authorFlairTextColor":"#FFCDD6F4","awardedCommentBackgroundColor":"#FF000000","awardsBackgroundColor":"#FFF9E2AF","awardsTextColor":"#FF181825","backgroundColor":"#FF000000","bottomAppBarBackgroundColor":"#00000000","bottomAppBarIconColor":"#FFCDD6F4","buttonTextColor":"#FFA6ADC8","cardViewBackgroundColor":"#FF000000","chipTextColor":"#FF181825","circularProgressBarBackground":"#FF181825","colorAccent":"#FF89B4FA","colorPrimary":"#FF000000","colorPrimaryDark":"#FF000000","colorPrimaryLightTheme":"#FF89B4FA","commentBackgroundColor":"#FF000000","commentColor":"#FFCDD6F4","commentIconAndInfoColor":"#FFA6ADC8","commentVerticalBarColor1":"#FF89B4FA","commentVerticalBarColor2":"#FFCBA6F7","commentVerticalBarColor3":"#FF94E2D5","commentVerticalBarColor4":"#FFF9E2AF","commentVerticalBarColor5":"#FFF38BA8","commentVerticalBarColor6":"#FFA6E3A1","commentVerticalBarColor7":"#FFFAB387","crosspostIconTint":"#FFF5C2E7","currentUser":"#FF94E2D5","dividerColor":"#FF9399B2","downvoted":"#FF89DCEB","fabIconColor":"#FF181825","flairBackgroundColor":"#FFA6E3A1","flairTextColor":"#FF181825","fullyCollapsedCommentBackgroundColor":"#FF11111B","isAmoledTheme":true,"isChangeStatusBarIconColorAfterToolbarCollapsedInImmersiveInterface":false,"isDarkTheme":true,"isLightNavBar":false,"isLightStatusBar":false,"isLightTheme":false,"linkColor":"#FFF5E0DC","lockedIconTint":"#FFFAB387","mediaIndicatorBackgroundColor":"#FF7C7F93","mediaIndicatorIconColor":"#FF11111B","moderator":"#FFA6E3A1","name":"Catppuccin Void","navBarColor":"#FF000000","noPreviewPostTypeBackgroundColor":"#FF7F849C","noPreviewPostTypeIconTint":"#FF7F849C","nsfwBackgroundColor":"#FFF38BA8","nsfwTextColor":"#FF181825","postContentColor":"#FFCDD6F4","postIconAndInfoColor":"#FFA6ADC8","postTitleColor":"#FFCDD6F4","postTypeBackgroundColor":"#FF89B4FA","postTypeTextColor":"#FF181825","primaryIconColor":"#FFCDD6F4","primaryTextColor":"#FFCDD6F4","readPostCardViewBackgroundColor":"#FF000000","readPostContentColor":"#FF7F849C","readPostTitleColor":"#FF7F849C","receivedMessageBackgroundColor":"#FF89DCEB","receivedMessageTextColor":"#FFCDD6F4","secondaryTextColor":"#FFA6ADC8","sendMessageIconColor":"#FF89DCEB","sentMessageBackgroundColor":"#FFA6E3A1","sentMessageTextColor":"#FFCDD6F4","singleCommentThreadBackgroundColor":"#FF000000","spoilerBackgroundColor":"#FFF5C2E7","spoilerTextColor":"#FF181825","stickiedPostIconTint":"#FF89B4FA","submitter":"#FFFAB387","subreddit":"#FFFAB387","subscribed":"#FFF38BA8","tabLayoutWithCollapsedCollapsingToolbarTabBackground":"#FF000000","tabLayoutWithCollapsedCollapsingToolbarTabIndicator":"#FFCDD6F4","tabLayoutWithCollapsedCollapsingToolbarTextColor":"#FFCDD6F4","tabLayoutWithExpandedCollapsingToolbarTabBackground":"#FF000000","tabLayoutWithExpandedCollapsingToolbarTabIndicator":"#FFCDD6F4","tabLayoutWithExpandedCollapsingToolbarTextColor":"#FFCDD6F4","toolbarPrimaryTextAndIconColor":"#FFCDD6F4","toolbarSecondaryTextColor":"#FFA6ADC8","unreadMessageBackgroundColor":"#FF313244","unsubscribed":"#FF89B4FA","upvoteRatioIconTint":"#FF89B4FA","upvoted":"#FFFAB387","username":"#FFCBA6F7","voteAndReplyUnavailableButtonColor":"#FF7F849C"}`

Thank you!

**Comment by samnystrom** [comment]
Hi! Catppuccin port maintainer here. Unfortunately, OLED is not an official Catppuccin flavor and will not be included in any ports. If you would like to convert the theme to OLED, then you can take the mocha theme and perform the following text replacements:

- `#FF1E1E2E` -> `#FF000000`
- `#FF181825` -> `#FF010101`
- `#FF11111B` -> `#FF020202`

Hope this helps!

**Comment by ttmx** [comment]
Thank you, this is very nice of you! :)
